trivy-image:
  name: trivy-image
  runs-on: [self-hosted]
  steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Docker login
      uses: docker/login-action@v1
      with:
        registry: c.rzp.io
        username: ${{ secrets.HARBOR_DOCKER_USERNAME }}
        password: ${{ secrets.HARBOR_DOCKER_PASSWORD }}

    - name: Build an image from Dockerfile
      run: |
        docker build -t c.rzp.io/razorpay/payment-links:${{ github.sha }} --build-arg GIT_COMMIT_HASH=${{ github.sha }} --build-arg GIT_TOKEN=${{ secrets.GIT_TOKEN }} .

    - name: Run Trivy vulnerability scanner For Image
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: 'c.rzp.io/razorpay/payment-links:${{ github.sha }}'
        format: 'json'
        output: 'trivy-results.json'
        exit-code: 0
        hide-progress: false

    - name : Print Details
      run: |
        apt-get update
        apt-get install jq -y
        sleep 5
        cat trivy-results.json

    - name : push result to defect dojo
      run:
        using: 'docker'
        image: 'Dockerfile'